-- MySQL Script generated by MySQL Workbench
-- Thu May 28 18:05:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET @@global.time_zone = '+00:00';
SET @@session.time_zone = '+00:00';

-- -----------------------------------------------------
-- Schema SuiviKine
--
-- BDD pour l'application SuiviKine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SuiviKine`;
CREATE SCHEMA `SuiviKine` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `SuiviKine` ;

-- -----------------------------------------------------
-- Table `SuiviKine`.`Resident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuiviKine`.`Resident` (
  `nom` VARCHAR(100) NOT NULL DEFAULT "",
  `prenom` VARCHAR(100) NOT NULL DEFAULT "",
  `date_naissance` VARCHAR(10) NOT NULL DEFAULT "",
  `sexe` VARCHAR(1) NOT NULL DEFAULT "",
  `n_secu_sociale` VARCHAR(15) NOT NULL DEFAULT "",
  `medecin_prescripteur` VARCHAR(200) NOT NULL DEFAULT "",
  `equipe_kine` INT NOT NULL DEFAULT 0,
  `date_prescription` VARCHAR(10) NULL,
  `prescription_quantitative` VARCHAR(3) NULL,
  `renouvellement` VARCHAR(3) NULL,
  `indication_medicale` VARCHAR(289) NULL,
  `nb_protocole_therapeutique` INT NULL,
  `rythme_seances` INT NULL,
  `travail_groupe` VARCHAR(3) NULL,
  `date_premiere_seance` VARCHAR(10) NULL,
  `techniques` VARCHAR(314) NULL,
  `intitules` VARCHAR(40) NULL,
  `demarrage_date` VARCHAR(10) NULL,
  `intermediaire_date` VARCHAR(10) NULL,
  `finale_date` VARCHAR(10) NULL,
  `articulairesD` TEXT NULL,
  `articulairesI` TEXT NULL,
  `articulairesF` TEXT NULL,
  `force_musculaireD` TEXT NULL,
  `force_musculaireI` TEXT NULL,
  `force_musculaireF` TEXT NULL,
  `douleursD` TEXT NULL,
  `douleursI` TEXT NULL,
  `douleursF` TEXT NULL,
  `trophiquesD` TEXT NULL,
  `trophiquesI` TEXT NULL,
  `trophiquesF` TEXT NULL,
  `bilan_deficits_fonctionnelsD` TEXT NULL,
  `bilan_deficits_fonctionnelsI` TEXT NULL,
  `bilan_deficits_fonctionnelsF` TEXT NULL,
  `autres_problemesD` TEXT NULL,
  `autres_problemesI` TEXT NULL,
  `autres_problemesF` TEXT NULL,
  `objectifs_court_termeD` TEXT NULL,
  `objectifs_court_termeI` TEXT NULL,
  `objectifs_court_termeF` TEXT NULL,
  `objectifs_moyen_termeD` TEXT NULL,
  `objectifs_moyen_termeI` TEXT NULL,
  `objectifs_moyen_termeF` TEXT NULL,
  `objectifs_long_termeD` TEXT NULL,
  `objectifs_long_termeI` TEXT NULL,
  `objectifs_long_termeF` TEXT NULL,
  `diagnosticD` TEXT NULL,
  `diagnosticI` TEXT NULL,
  `diagnosticF` TEXT NULL,
  `conseilsD` TEXT NULL,
  `conseilsI` TEXT NULL,
  `conseilsF` TEXT NULL,
  `propositionsD` TEXT NULL,
  `propositionsI` TEXT NULL,
  `propositionsF` TEXT NULL,
  `commentairesD` TEXT NULL,
  `commentairesI` TEXT NULL,
  `cotation` VARCHAR(50) NULL,
  `archive` VARCHAR(3) NOT NULL DEFAULT "Non",
  PRIMARY KEY (`nom`, `prenom`, `date_naissance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuiviKine`.`EquipeKine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuiviKine`.`Equipe_kine` (
  `id_equipe_kine` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200) NOT NULL DEFAULT "Equipe kiné",
  `login` VARCHAR(200) NOT NULL DEFAULT "login",
  `mdp` VARCHAR(200) NOT NULL DEFAULT "mdp",
  PRIMARY KEY (`id_equipe_kine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SuiviKine`.`Medecin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuiviKine`.`Medecin` (
  `id_medecin` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(200), 
  PRIMARY KEY (`id_medecin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Valeurs
-- -----------------------------------------------------
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Equipes kiné
-- -----------------------------------------------------
INSERT INTO `SuiviKine`.`Equipe_kine` (nom, login, mdp) VALUES ("admin", "admin", "mdpAdmin");
INSERT INTO `SuiviKine`.`Equipe_kine` (nom, login, mdp) VALUES ("Santenac", "equipe1", "mdp1");
INSERT INTO `SuiviKine`.`Equipe_kine` (nom, login, mdp) VALUES ("Martin", "equipe2", "mdp2");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;